driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[omusubi]
    #attributes: {docroot: "/var/www/"}